name: Deploy to Sakura Server

on:
  push:
    branches:
      - master  # mainからmasterに変更
  pull_request:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: cd src && npm install  # srcに移動して依存関係をインストール

    - name: Generate static files
      run: cd src && npm run generate  # srcに移動して静的ファイルを生成

    - name: Upload to Sakura Server
      uses: SamKirkland/FTP-Deploy-Action@4.3.1
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: src/dist  # distがsrcの中にある場合、パスを修正
        server-dir: /home/visionary-design/www/dev
